#!/bin/bash

for f in ./R/*~; do
    rm -f $f
done

for f in ./man/*~; do
    rm -f $f
done

for f in ./inst/*~; do
    rm -f $f
done

for f in ./date/*~; do
    rm -f $f
done

for f in ./sim/*~; do
    rm -f $f
done

for f in *~; do
    rm -f $f
done

find . -name "DEADJOE" -exec rm -f {} \;

exit 0
